docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Introduction: intro.md
    - Validators:
      - Barcode: validators/barcode.md
      - Date: validators/date.md
      - NotEmpty: validators/not-empty.md
      - UUID: validators/uuid.md
site_name: zend-datavalidator
site_description: 'General purpose, decoupled validation component.'
repo_url: 'https://github.com/zendframework/zend-datavalidator'
copyright: 'Copyright (c) 2017-2018 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
